name: prerelease

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      release:
        description: 'Create a release (not prerelease)'
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Build ah
        run: make -j ah

      - name: Generate checksums
        run: |
          cd o/bin
          sha256sum ah > SHA256SUMS

      - name: Get version
        id: version
        run: echo "tag=$(date -u +%Y-%m-%d)-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete "${{ steps.version.outputs.tag }}" --yes || true
          gh release create "${{ steps.version.outputs.tag }}" \
            --title "${{ steps.version.outputs.tag }}" \
            ${{ inputs.release != true && '--prerelease' || '' }} \
            o/bin/ah \
            o/bin/SHA256SUMS
